/Users/linchengbo/Downloads/TrollStore-2/TrollHelper/.theos/obj/../RootHelper/main.m.e09fbad0.o: \
  ../RootHelper/main.m /opt/theos/Prefix.pch ../RootHelper/unarchive.h \
  ../RootHelper/uicache.h ../Shared/TSUtil.h ../Shared/CoreServices.h \
  ../RootHelper/devmode.h ../RootHelper/jit.h \
  /opt/theos/vendor/include/SpringBoardServices/SpringBoardServices.h \
  /opt/theos/vendor/include/FrontBoardServices/module.modulemap \
  /opt/theos/vendor/include/BaseBoard/module.modulemap \
  /opt/theos/vendor/include/BaseBoard/BaseBoard.h \
  /opt/theos/vendor/include/BaseBoard/BSAction.h \
  /opt/theos/vendor/include/BaseBoard/BSDescriptionProviding.h \
  /opt/theos/vendor/include/BaseBoard/BSSettingDescriptionProvider.h \
  /opt/theos/vendor/include/BaseBoard/BSXPCCoding.h \
  /opt/theos/vendor/include/BaseBoard/BSAuditToken.h \
  /opt/theos/vendor/include/BaseBoard/BSBaseXPCClient.h \
  /opt/theos/vendor/include/BaseBoard/BSMutableSettings.h \
  /opt/theos/vendor/include/BaseBoard/BSSettings.h \
  /opt/theos/vendor/include/BaseBoard/BSPlatform.h \
  /opt/theos/vendor/include/BaseBoard/BSProcessHandle.h \
  /opt/theos/vendor/include/FrontBoardServices/FrontBoardServices.h \
  /opt/theos/vendor/include/FrontBoardServices/FBSDisplay.h \
  /opt/theos/vendor/include/FrontBoardServices/FBSMutableSceneSettings.h \
  /opt/theos/vendor/include/FrontBoardServices/FBSSceneSettings.h \
  /opt/theos/vendor/include/FrontBoardServices/FBSOpenApplicationOptions.h \
  /opt/theos/vendor/include/FrontBoardServices/FBSProcessHandle.h \
  /opt/theos/vendor/include/FrontBoardServices/FBSSceneSettingsDiff.h \
  /opt/theos/vendor/include/FrontBoardServices/FBSSystemService.h \
  /opt/theos/vendor/include/libroot.h \
  /opt/theos/vendor/include/libroot/module.modulemap \
  /opt/theos/vendor/include/libroot/libroot.h

/opt/theos/Prefix.pch:

../RootHelper/unarchive.h:

../RootHelper/uicache.h:

../Shared/TSUtil.h:

../Shared/CoreServices.h:

../RootHelper/devmode.h:

../RootHelper/jit.h:

/opt/theos/vendor/include/SpringBoardServices/SpringBoardServices.h:

/opt/theos/vendor/include/FrontBoardServices/module.modulemap:

/opt/theos/vendor/include/BaseBoard/module.modulemap:

/opt/theos/vendor/include/BaseBoard/BaseBoard.h:

/opt/theos/vendor/include/BaseBoard/BSAction.h:

/opt/theos/vendor/include/BaseBoard/BSDescriptionProviding.h:

/opt/theos/vendor/include/BaseBoard/BSSettingDescriptionProvider.h:

/opt/theos/vendor/include/BaseBoard/BSXPCCoding.h:

/opt/theos/vendor/include/BaseBoard/BSAuditToken.h:

/opt/theos/vendor/include/BaseBoard/BSBaseXPCClient.h:

/opt/theos/vendor/include/BaseBoard/BSMutableSettings.h:

/opt/theos/vendor/include/BaseBoard/BSSettings.h:

/opt/theos/vendor/include/BaseBoard/BSPlatform.h:

/opt/theos/vendor/include/BaseBoard/BSProcessHandle.h:

/opt/theos/vendor/include/FrontBoardServices/FrontBoardServices.h:

/opt/theos/vendor/include/FrontBoardServices/FBSDisplay.h:

/opt/theos/vendor/include/FrontBoardServices/FBSMutableSceneSettings.h:

/opt/theos/vendor/include/FrontBoardServices/FBSSceneSettings.h:

/opt/theos/vendor/include/FrontBoardServices/FBSOpenApplicationOptions.h:

/opt/theos/vendor/include/FrontBoardServices/FBSProcessHandle.h:

/opt/theos/vendor/include/FrontBoardServices/FBSSceneSettingsDiff.h:

/opt/theos/vendor/include/FrontBoardServices/FBSSystemService.h:

/opt/theos/vendor/include/libroot.h:

/opt/theos/vendor/include/libroot/module.modulemap:

/opt/theos/vendor/include/libroot/libroot.h:
