/Users/linchengbo/Downloads/TrollStore-2/TrollHelper/.theos/obj/../RootHelper/unarchive.m.e09fbad0.o: \
  ../RootHelper/unarchive.m /opt/theos/Prefix.pch \
  ../RootHelper/unarchive.h /usr/local/opt/libarchive/include/archive.h \
  /usr/local/opt/libarchive/include/archive_entry.h

/opt/theos/Prefix.pch:

../RootHelper/unarchive.h:

/usr/local/opt/libarchive/include/archive.h:

/usr/local/opt/libarchive/include/archive_entry.h:
