/Users/linchengbo/Downloads/TrollStore-2/RootHelper/.theos/obj/../ChOma/src/FAT.c.371660b0.o: \
  ../ChOma/src/FAT.c /opt/theos/Prefix.pch ../ChOma/src/FAT.h \
  ../ChOma/src/MemoryStream.h ../ChOma/src/MachO.h \
  ../ChOma/src/MachOByteOrder.h ../ChOma/src/FileStream.h

/opt/theos/Prefix.pch:

../ChOma/src/FAT.h:

../ChOma/src/MemoryStream.h:

../ChOma/src/MachO.h:

../ChOma/src/MachOByteOrder.h:

../ChOma/src/FileStream.h:
