/Users/linchengbo/Downloads/TrollStore-2/RootHelper/.theos/obj/../ChOma/src/PatchFinder.c.371660b0.o: \
  ../ChOma/src/PatchFinder.c /opt/theos/Prefix.pch \
  ../ChOma/src/PatchFinder.h ../ChOma/src/MachO.h \
  ../ChOma/src/MemoryStream.h ../ChOma/src/FAT.h ../ChOma/src/Util.h \
  ../ChOma/src/PatchFinder_arm64.h

/opt/theos/Prefix.pch:

../ChOma/src/PatchFinder.h:

../ChOma/src/MachO.h:

../ChOma/src/MemoryStream.h:

../ChOma/src/FAT.h:

../ChOma/src/Util.h:

../ChOma/src/PatchFinder_arm64.h:
