/Users/linchengbo/Downloads/TrollStore-2/TrollStore/.theos/obj/../Shared/TSUtil.m.a535d105.o: \
  ../Shared/TSUtil.m /opt/theos/Prefix.pch ../Shared/TSUtil.h \
  ../Shared/CoreServices.h /opt/theos/vendor/include/libroot.h \
  /opt/theos/vendor/include/libroot/module.modulemap \
  /opt/theos/vendor/include/libroot/libroot.h

/opt/theos/Prefix.pch:

../Shared/TSUtil.h:

../Shared/CoreServices.h:

/opt/theos/vendor/include/libroot.h:

/opt/theos/vendor/include/libroot/module.modulemap:

/opt/theos/vendor/include/libroot/libroot.h:
